name: action-publish

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Dependencies
              run: sudo apt install --no-install-recommends ca-certificates qtbase5-dev qtbase5-private-dev git cmake make gcc g++ pkg-config libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libxi-dev libxrandr-dev libudev-dev libevdev-dev libsfml-dev libminiupnpc-dev libmbedtls-dev libcurl4-openssl-dev libhidapi-dev libsystemd-dev libbluetooth-dev libasound2-dev libpulse-dev libpugixml-dev libbz2-dev libzstd-dev liblzo2-dev libpng-dev libusb-1.0-0-dev gettext
            - name: Clone Dolphin
              run: git clone https://github.com/dolphin-emu/dolphin.git dolphin-emu && cd dolphin-emu
            - name: Submodules
              run: git submodule update --init 
            - name: (debug) ls
              run: ls
            - name: Configure
              run: mkdir Build && cd Build && cmake -Dbindir=../Binary/Linux -Ddatadir=../Binary/Linux ..
            - name: Make!!!
              run: make -j$(nproc) 
            - name: (debug) ls
              run: ls
